// generated by stringer -type=LoopBound; DO NOT EDIT

package migoextract

import "fmt"

const _LoopBound_name = "UnknownStaticDynamic"

var _LoopBound_index = [...]uint8{0, 7, 13, 20}

func (i LoopBound) String() string {
	if i < 0 || i >= LoopBound(len(_LoopBound_index)-1) {
		return fmt.Sprintf("LoopBound(%d)", i)
	}
	return _LoopBound_name[_LoopBound_index[i]:_LoopBound_index[i+1]]
}
