// generated by stringer -type=LoopState; DO NOT EDIT

package migoextract

import "fmt"

const _LoopState_name = "NonLoopEnterBodyExit"

var _LoopState_index = [...]uint8{0, 7, 12, 16, 20}

func (i LoopState) String() string {
	if i < 0 || i >= LoopState(len(_LoopState_index)-1) {
		return fmt.Sprintf("LoopState(%d)", i)
	}
	return _LoopState_name[_LoopState_index[i]:_LoopState_index[i+1]]
}
